version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: noiffion/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: noiffion/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed
    image: noiffion/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend
    image: noiffion/udacity-frontend