version: "3"
services:
  reverseproxy:
      image: noiffion/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: noiffion/udacity-restapi-user
    tty: true
    env_file:
      - .env
  backend-feed:
    tty: true
    image: noiffion/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - .env
  frontend:
    image: noiffion/udacity-frontend
    ports:
      - "8100:80"
